export const metadata = {
  title: "Next.js",

  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  console.log("montando layout");

  return (
    <html lang="en">
      <body>
        <Home />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export function Footer() {
  return (
    <footer>
      <p>© 2024 Menu do Doutor - Todos os direitos reservados</p>
    </footer>
  );
}

export function Home() {
  return (
    <div>
      <div>Menu do Doutor</div>
      <div>
        <h1>Eh o Doutor</h1>
      </div>
    </div>
  );
}
